### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by shreyasminocha** [plibither8/wayback-sitemap-archive#1]
Hello!

Is there a reason for not publishing this to npm?

---

I always needed exactly this, yet it didn't strike to me to automate it. Thanks!

**Comment by plibither8** [comment]
Hi! I'll be honest, publishing to npm did not come to my mind. I'll publish it by the end of the day hopefully and inform you. Thanks!

**Comment by plibither8** [comment]
Hi! I've finally published the package :D, and added usage instructions to the README. Thanks for the suggestion!

**Comment by shreyasminocha** [comment]
Thanks!
